image: ghcr.io/cirruslabs/flutter

lints_front:
  stage: lints
  script:
    - cd smarthike
    - flutter pub get
    - flutter clean
    - flutter analyze --no-fatal-infos --no-fatal-warnings
  only:
    changes:
      - smarthike/**/*

tests_front:
  stage: tests
  script:
    - cd smarthike
    - flutter pub get
    - flutter clean
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  artifacts:
    paths:
      - coverage
    expire_in: 10 mins
  only:
    changes:
      - smarthike/**/*

build_front:
  stage: build
  script:
    - cd smarthike
    - flutter pub get
    - flutter clean
    - flutter build apk --release --build-number ${CI_JOB_ID:0:8}
    - flutter build appbundle --release --build-number ${CI_JOB_ID:0:8}
    - mv build/app/outputs/flutter-apk/app-release.apk build/artifacts/app-release-${CI_JOB_ID:0:8}.apk
  artifacts:
    paths:
      - build/artifacts/
    expire_in: 2 days
  only:
    - main