stages:
  - lints
  - tests
  - build

include:
  - "smarthike/.ci/.gitlab-flutter.yml"
  - "backoffice/.ci/.backend.yml"

pages:
  image: node:alpine
  stage: build
  script:
  - npm install -g redoc-cli
  - redoc-cli bundle -o public/index.html backoffice/swagger.json
  artifacts:
    paths:
    - public
  only:
    - develop
  rules:
    - changes:
        - backoffice/swagger.json