services:
  backend_python:
    build: .docker/python
    volumes:
      - ./backoffice:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      SECRET_KEY: "s3cr3t"
      JWT_KEY: "s3cr3t"
      DATABASE_URI: "mysql://yep600:yep600@database/yep600"
    depends_on:
      - database

  database:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_USER: "yep600"
      MARIADB_PASSWORD: "yep600"
      MARIADB_DATABASE: "yep600"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 1G
    depends_on:
      - database

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./backoffice/swagger.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
    depends_on:
      - database

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  minio:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
      - '8900:8900'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - 'minio_data:/data/minio'
    command: 'minio server /data/minio --console-address ":8900"'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      retries: 3
      timeout: 5s
  
  minio-init:
    image: quay.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio password;
      /usr/bin/mc admin config set myminio/ region name=fr-par;
      /usr/bin/mc admin service restart myminio/;
      /usr/bin/mc mb myminio/smarthike;
      /usr/bin/mc anonymous set public myminio/smarthike; 
      exit 0;
      "

volumes:
  db_data: {}
  minio_data: {}
