// Mocks generated by Mockito 5.4.4 from annotations
// in smarthike/test/providers/hike_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smarthike/api/smarthike_api.dart' as _i2;
import 'package:smarthike/models/hike.dart' as _i6;
import 'package:smarthike/models/paginated_hike.dart' as _i5;
import 'package:smarthike/services/hike_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HikeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHikeService extends _i1.Mock implements _i3.HikeService {
  MockHikeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i2.ApiService);

  @override
  _i4.Future<_i5.PaginatedHike?> getListHikes(int? page) => (super.noSuchMethod(
        Invocation.method(
          #getListHikes,
          [page],
        ),
        returnValue: _i4.Future<_i5.PaginatedHike?>.value(),
      ) as _i4.Future<_i5.PaginatedHike?>);

  @override
  _i4.Future<List<_i3.Ways>> getHikeGeometry(int? hikeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHikeGeometry,
          [hikeId],
        ),
        returnValue: _i4.Future<List<_i3.Ways>>.value(<_i3.Ways>[]),
      ) as _i4.Future<List<_i3.Ways>>);

  @override
  _i4.Future<List<_i6.Hike>> getAllHikes() => (super.noSuchMethod(
        Invocation.method(
          #getAllHikes,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Hike>>.value(<_i6.Hike>[]),
      ) as _i4.Future<List<_i6.Hike>>);
}
