// Mocks generated by Mockito 5.4.4 from annotations
// in smarthike/test/providers/hike_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:smarthike/api/smarthike_api.dart' as _i2;
import 'package:smarthike/models/hike.dart' as _i3;
import 'package:smarthike/models/paginated_hike.dart' as _i6;
import 'package:smarthike/services/hike_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHike_1 extends _i1.SmartFake implements _i3.Hike {
  _FakeHike_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HikeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHikeService extends _i1.Mock implements _i4.HikeService {
  MockHikeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i2.ApiService);

  @override
  _i5.Future<List<String>> searchCities(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchCities,
          [query],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<Map<String, dynamic>?> getCityCoordinates(String? cityName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCityCoordinates,
          [cityName],
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<_i6.PaginatedHike?> getListHikes(
    int? page, {
    required Map<String, dynamic>? filters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListHikes,
          [page],
          {#filters: filters},
        ),
        returnValue: _i5.Future<_i6.PaginatedHike?>.value(),
      ) as _i5.Future<_i6.PaginatedHike?>);

  @override
  _i5.Future<List<_i4.Ways>> getHikeGeometry(int? hikeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHikeGeometry,
          [hikeId],
        ),
        returnValue: _i5.Future<List<_i4.Ways>>.value(<_i4.Ways>[]),
      ) as _i5.Future<List<_i4.Ways>>);

  @override
  _i5.Future<List<_i3.Hike>> getAllHikes() => (super.noSuchMethod(
        Invocation.method(
          #getAllHikes,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Hike>>.value(<_i3.Hike>[]),
      ) as _i5.Future<List<_i3.Hike>>);

  @override
  _i5.Future<String> uploadHikeImage(
    int? hikeId,
    _i7.File? file,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadHikeImage,
          [
            hikeId,
            file,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #uploadHikeImage,
            [
              hikeId,
              file,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i3.Hike> getHike(int? hikeId) => (super.noSuchMethod(
        Invocation.method(
          #getHike,
          [hikeId],
        ),
        returnValue: _i5.Future<_i3.Hike>.value(_FakeHike_1(
          this,
          Invocation.method(
            #getHike,
            [hikeId],
          ),
        )),
      ) as _i5.Future<_i3.Hike>);
}
