// Mocks generated by Mockito 5.4.4 from annotations
// in smarthike/test/providers/user_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:logger/logger.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:smarthike/api/smarthike_api.dart' as _i2;
import 'package:smarthike/models/user.dart' as _i5;
import 'package:smarthike/services/auth_service.dart' as _i6;
import 'package:smarthike/utils/shared_preferences_util.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiService_0 extends _i1.SmartFake implements _i2.ApiService {
  _FakeApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferencesUtil_1 extends _i1.SmartFake
    implements _i3.SharedPreferencesUtil {
  _FakeSharedPreferencesUtil_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_2 extends _i1.SmartFake implements _i4.Logger {
  _FakeLogger_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_3 extends _i1.SmartFake implements _i5.User {
  _FakeUser_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i6.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiService get apiService => (super.noSuchMethod(
        Invocation.getter(#apiService),
        returnValue: _FakeApiService_0(
          this,
          Invocation.getter(#apiService),
        ),
      ) as _i2.ApiService);

  @override
  _i3.SharedPreferencesUtil get sharedPreferencesUtil => (super.noSuchMethod(
        Invocation.getter(#sharedPreferencesUtil),
        returnValue: _FakeSharedPreferencesUtil_1(
          this,
          Invocation.getter(#sharedPreferencesUtil),
        ),
      ) as _i3.SharedPreferencesUtil);

  @override
  _i4.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_2(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i4.Logger);

  @override
  _i7.Future<_i5.User?> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i7.Future<_i5.User?>.value(),
      ) as _i7.Future<_i5.User?>);

  @override
  _i7.Future<_i5.User?> register(
    String? firstname,
    String? lastname,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            firstname,
            lastname,
            email,
            password,
          ],
        ),
        returnValue: _i7.Future<_i5.User?>.value(),
      ) as _i7.Future<_i5.User?>);

  @override
  _i7.Future<void> deleteUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.User?> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<_i5.User?>.value(),
      ) as _i7.Future<_i5.User?>);

  @override
  _i7.Future<_i5.User?> getUserData(String? token) => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [token],
        ),
        returnValue: _i7.Future<_i5.User?>.value(),
      ) as _i7.Future<_i5.User?>);

  @override
  _i7.Future<_i5.User> updateUser(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i7.Future<_i5.User>.value(_FakeUser_3(
          this,
          Invocation.method(
            #updateUser,
            [user],
          ),
        )),
      ) as _i7.Future<_i5.User>);
}
