build_back:
  image: alpine
  stage: build
  script:
    - cd backoffice
    - echo "Build OK"
  only:
    - main

lints_back:
  stage: lints
  image: alpine
  script:
    - cd backoffice
    - echo "Lint OK"
  rules:
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_COMMIT_BRANCH != "main"'
      changes:
        - backoffice/**/*

tests_back:
  image: docker:latest
  stage: tests
  services:
    - name: docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: "tcp://thedockerhost:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - cd backoffice
    - apk add --no-cache make gcc g++ bash docker-compose
    - cd ../
    - make build ENV=test
    - sleep 30
    - make test ENV=test
  rules:
    - if: '$CI_COMMIT_BRANCH != "develop" && $CI_COMMIT_BRANCH != "main"'
      changes:
        - backoffice/**/*