lints_back:
  stage: lints
  image: alpine
  script:
    - cd backoffice
    - echo "Lint OK"
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^(feature|feat|fix|hotfix)/"
      when: manual
    - if: "$CI_MERGE_REQUEST_IID || $CI_COMMIT_BRANCH =~ /^(develop|main)/"
      when: always

tests_back:
  image: docker:latest
  stage: tests
  services:
    - name: docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: "tcp://thedockerhost:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - cd backoffice
    - apk add --no-cache make gcc g++ bash docker-compose
    - cd ../
    - make build ENV=ci
    - sleep 60
    - make install ENV=ci
    - make test ENV=ci
  rules:  
    - if: "$CI_MERGE_REQUEST_IID || $CI_COMMIT_BRANCH =~ /^(develop|main)/"
      when: always
    - if: "$CI_COMMIT_BRANCH =~ /^(feature|feat|fix|hotfix)/"
      when: manual