build_back:docker:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--tls=false","--mtu=1450"]
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^(feature|feat|fix|hotfix)/"
      when: manual
    - if: "$CI_COMMIT_BRANCH =~ /^(develop|main)/"
      when: always
    - if: "$CI_MERGE_REQUEST_IID || $CI_COMMIT_BRANCH =~ /^(develop|main)/"
      when: always
      changes:
        - backoffice/**/*
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ''
    DOCKER_DRIVER: overlay2
    DOCKER_BUILDKIT: 1
    DOCKER_CLI_EXPERIMENTAL: enabled 
  script: 
    - docker buildx create --use
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx build -t $CI_REGISTRY_IMAGE/backend-tyep600-nan1:$(echo $CI_COMMIT_REF_NAME | tr '[:upper:]' '[:lower:]' | sed 's/\//-/g') -f .docker/python/Dockerfile backoffice/ --platform linux/amd64,linux/arm64 --push
  needs:
    - job: lints_back
      optional: false
    - job: tests_back
      optional: false